using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InspectNow.Infrastructure.Persistence.Migrations;

/// <summary>
/// Data-preserving UUID-to-bigint conversion, plus pending answer properties.
/// Keep the three earlier migrations unchanged. Do not scaffold a replacement.
/// </summary>
public partial class UseNumericEntityIdsAndAddAnswers : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            -- Executed inside the EF migration transaction. Stop API writes first.
            SET LOCAL lock_timeout = '15s';
            LOCK TABLE public."InspectionTemplates", public."TemplateQuestions",
                public."Inspections", public."InspectionQuestions" IN ACCESS EXCLUSIVE MODE;
            
            -- Historical conversion audit only; EF does not map this table.
            -- UUIDs here are old identifiers, never active entity primary keys.
            CREATE TABLE public."__LegacyIdMap" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "EntityTable" text NOT NULL,
                "OldId" uuid NOT NULL,
                "NewId" bigint NOT NULL,
                CONSTRAINT "UQ_LegacyIdMap_Old" UNIQUE ("EntityTable", "OldId"),
                CONSTRAINT "UQ_LegacyIdMap_New" UNIQUE ("EntityTable", "NewId")
            );
            
            CREATE TEMP TABLE "InspectNow_IdConversionCounts" (
                "EntityTable" text PRIMARY KEY, "RowCount" bigint NOT NULL
            ) ON COMMIT DROP;
            
            INSERT INTO "InspectNow_IdConversionCounts"
            SELECT 'InspectionTemplates', count(*) FROM public."InspectionTemplates";
            
            INSERT INTO "InspectNow_IdConversionCounts"
            SELECT 'TemplateQuestions', count(*) FROM public."TemplateQuestions";
            
            INSERT INTO "InspectNow_IdConversionCounts"
            SELECT 'Inspections', count(*) FROM public."Inspections";
            
            INSERT INTO "InspectNow_IdConversionCounts"
            SELECT 'InspectionQuestions', count(*) FROM public."InspectionQuestions";
            
            INSERT INTO public."__LegacyIdMap" ("EntityTable", "OldId", "NewId")
            SELECT 'InspectionTemplates', "OldId", row_number() OVER (ORDER BY "OldId")
            FROM (
                SELECT "Id" AS "OldId" FROM public."InspectionTemplates"
            ) AS source_ids;
            
            INSERT INTO public."__LegacyIdMap" ("EntityTable", "OldId", "NewId")
            SELECT 'TemplateQuestions', "OldId", row_number() OVER (ORDER BY "OldId")
            FROM (
                SELECT "Id" AS "OldId" FROM public."TemplateQuestions"
                UNION
                SELECT "SourceQuestionId" FROM public."InspectionQuestions"
            ) AS source_ids;
            
            INSERT INTO public."__LegacyIdMap" ("EntityTable", "OldId", "NewId")
            SELECT 'Inspections', "OldId", row_number() OVER (ORDER BY "OldId")
            FROM (
                SELECT "Id" AS "OldId" FROM public."Inspections"
            ) AS source_ids;
            
            INSERT INTO public."__LegacyIdMap" ("EntityTable", "OldId", "NewId")
            SELECT 'InspectionQuestions', "OldId", row_number() OVER (ORDER BY "OldId")
            FROM (
                SELECT "Id" AS "OldId" FROM public."InspectionQuestions"
            ) AS source_ids;
            
            ALTER TABLE public."InspectionTemplates" ADD COLUMN "Id_New" bigint;
            UPDATE public."InspectionTemplates" AS entity
            SET "Id_New" = mapping."NewId"
            FROM public."__LegacyIdMap" AS mapping
            WHERE mapping."EntityTable" = 'InspectionTemplates' AND mapping."OldId" = entity."Id";
            ALTER TABLE public."InspectionTemplates" ALTER COLUMN "Id_New" SET NOT NULL;
            
            ALTER TABLE public."TemplateQuestions" ADD COLUMN "Id_New" bigint;
            UPDATE public."TemplateQuestions" AS entity
            SET "Id_New" = mapping."NewId"
            FROM public."__LegacyIdMap" AS mapping
            WHERE mapping."EntityTable" = 'TemplateQuestions' AND mapping."OldId" = entity."Id";
            ALTER TABLE public."TemplateQuestions" ALTER COLUMN "Id_New" SET NOT NULL;
            
            ALTER TABLE public."Inspections" ADD COLUMN "Id_New" bigint;
            UPDATE public."Inspections" AS entity
            SET "Id_New" = mapping."NewId"
            FROM public."__LegacyIdMap" AS mapping
            WHERE mapping."EntityTable" = 'Inspections' AND mapping."OldId" = entity."Id";
            ALTER TABLE public."Inspections" ALTER COLUMN "Id_New" SET NOT NULL;
            
            ALTER TABLE public."InspectionQuestions" ADD COLUMN "Id_New" bigint;
            UPDATE public."InspectionQuestions" AS entity
            SET "Id_New" = mapping."NewId"
            FROM public."__LegacyIdMap" AS mapping
            WHERE mapping."EntityTable" = 'InspectionQuestions' AND mapping."OldId" = entity."Id";
            ALTER TABLE public."InspectionQuestions" ALTER COLUMN "Id_New" SET NOT NULL;
            
            ALTER TABLE public."TemplateQuestions" ADD COLUMN "InspectionTemplateId_New" bigint;
            UPDATE public."TemplateQuestions" AS entity
            SET "InspectionTemplateId_New" = mapping."NewId"
            FROM public."__LegacyIdMap" AS mapping
            WHERE mapping."EntityTable" = 'InspectionTemplates' AND mapping."OldId" = entity."InspectionTemplateId";
            -- Abort rather than lose an unmapped relationship.
            ALTER TABLE public."TemplateQuestions" ALTER COLUMN "InspectionTemplateId_New" SET NOT NULL;
            
            ALTER TABLE public."Inspections" ADD COLUMN "TemplateId_New" bigint;
            UPDATE public."Inspections" AS entity
            SET "TemplateId_New" = mapping."NewId"
            FROM public."__LegacyIdMap" AS mapping
            WHERE mapping."EntityTable" = 'InspectionTemplates' AND mapping."OldId" = entity."TemplateId";
            -- Abort rather than lose an unmapped relationship.
            ALTER TABLE public."Inspections" ALTER COLUMN "TemplateId_New" SET NOT NULL;
            
            ALTER TABLE public."InspectionQuestions" ADD COLUMN "InspectionId_New" bigint;
            UPDATE public."InspectionQuestions" AS entity
            SET "InspectionId_New" = mapping."NewId"
            FROM public."__LegacyIdMap" AS mapping
            WHERE mapping."EntityTable" = 'Inspections' AND mapping."OldId" = entity."InspectionId";
            -- Abort rather than lose an unmapped relationship.
            ALTER TABLE public."InspectionQuestions" ALTER COLUMN "InspectionId_New" SET NOT NULL;
            
            ALTER TABLE public."InspectionQuestions" ADD COLUMN "SourceQuestionId_New" bigint;
            UPDATE public."InspectionQuestions" AS entity
            SET "SourceQuestionId_New" = mapping."NewId"
            FROM public."__LegacyIdMap" AS mapping
            WHERE mapping."EntityTable" = 'TemplateQuestions' AND mapping."OldId" = entity."SourceQuestionId";
            -- Abort rather than lose an unmapped relationship.
            ALTER TABLE public."InspectionQuestions" ALTER COLUMN "SourceQuestionId_New" SET NOT NULL;
            
            ALTER TABLE public."TemplateQuestions" DROP CONSTRAINT "FK_TemplateQuestions_InspectionTemplates_InspectionTemplateId";
            
            ALTER TABLE public."Inspections" DROP CONSTRAINT "FK_Inspections_InspectionTemplates_TemplateId";
            
            ALTER TABLE public."InspectionQuestions" DROP CONSTRAINT "FK_InspectionQuestions_Inspections_InspectionId";
            
            ALTER TABLE public."InspectionTemplates" DROP CONSTRAINT "PK_InspectionTemplates";
            
            ALTER TABLE public."TemplateQuestions" DROP CONSTRAINT "PK_TemplateQuestions";
            
            ALTER TABLE public."Inspections" DROP CONSTRAINT "PK_Inspections";
            
            ALTER TABLE public."InspectionQuestions" DROP CONSTRAINT "PK_InspectionQuestions";
            
            ALTER TABLE public."TemplateQuestions" DROP COLUMN "InspectionTemplateId";
            ALTER TABLE public."TemplateQuestions" RENAME COLUMN "InspectionTemplateId_New" TO "InspectionTemplateId";
            
            ALTER TABLE public."Inspections" DROP COLUMN "TemplateId";
            ALTER TABLE public."Inspections" RENAME COLUMN "TemplateId_New" TO "TemplateId";
            
            ALTER TABLE public."InspectionQuestions" DROP COLUMN "InspectionId";
            ALTER TABLE public."InspectionQuestions" RENAME COLUMN "InspectionId_New" TO "InspectionId";
            
            ALTER TABLE public."InspectionQuestions" DROP COLUMN "SourceQuestionId";
            ALTER TABLE public."InspectionQuestions" RENAME COLUMN "SourceQuestionId_New" TO "SourceQuestionId";
            
            ALTER TABLE public."InspectionTemplates" DROP COLUMN "Id";
            ALTER TABLE public."InspectionTemplates" RENAME COLUMN "Id_New" TO "Id";
            ALTER TABLE public."InspectionTemplates" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
            ALTER TABLE public."InspectionTemplates" ADD CONSTRAINT "PK_InspectionTemplates" PRIMARY KEY ("Id");
            -- Reserve IDs for historical source questions too, even if their source was deleted.
            SELECT setval(
                pg_get_serial_sequence('public."InspectionTemplates"', 'Id')::regclass,
                GREATEST(COALESCE(max("NewId"), 0), 1),
                count(*) > 0)
            FROM public."__LegacyIdMap" WHERE "EntityTable" = 'InspectionTemplates';
            
            ALTER TABLE public."TemplateQuestions" DROP COLUMN "Id";
            ALTER TABLE public."TemplateQuestions" RENAME COLUMN "Id_New" TO "Id";
            ALTER TABLE public."TemplateQuestions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
            ALTER TABLE public."TemplateQuestions" ADD CONSTRAINT "PK_TemplateQuestions" PRIMARY KEY ("Id");
            -- Reserve IDs for historical source questions too, even if their source was deleted.
            SELECT setval(
                pg_get_serial_sequence('public."TemplateQuestions"', 'Id')::regclass,
                GREATEST(COALESCE(max("NewId"), 0), 1),
                count(*) > 0)
            FROM public."__LegacyIdMap" WHERE "EntityTable" = 'TemplateQuestions';
            
            ALTER TABLE public."Inspections" DROP COLUMN "Id";
            ALTER TABLE public."Inspections" RENAME COLUMN "Id_New" TO "Id";
            ALTER TABLE public."Inspections" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
            ALTER TABLE public."Inspections" ADD CONSTRAINT "PK_Inspections" PRIMARY KEY ("Id");
            -- Reserve IDs for historical source questions too, even if their source was deleted.
            SELECT setval(
                pg_get_serial_sequence('public."Inspections"', 'Id')::regclass,
                GREATEST(COALESCE(max("NewId"), 0), 1),
                count(*) > 0)
            FROM public."__LegacyIdMap" WHERE "EntityTable" = 'Inspections';
            
            ALTER TABLE public."InspectionQuestions" DROP COLUMN "Id";
            ALTER TABLE public."InspectionQuestions" RENAME COLUMN "Id_New" TO "Id";
            ALTER TABLE public."InspectionQuestions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
            ALTER TABLE public."InspectionQuestions" ADD CONSTRAINT "PK_InspectionQuestions" PRIMARY KEY ("Id");
            -- Reserve IDs for historical source questions too, even if their source was deleted.
            SELECT setval(
                pg_get_serial_sequence('public."InspectionQuestions"', 'Id')::regclass,
                GREATEST(COALESCE(max("NewId"), 0), 1),
                count(*) > 0)
            FROM public."__LegacyIdMap" WHERE "EntityTable" = 'InspectionQuestions';
            
            ALTER TABLE public."TemplateQuestions" ADD CONSTRAINT "FK_TemplateQuestions_InspectionTemplates_InspectionTemplateId"
            FOREIGN KEY ("InspectionTemplateId") REFERENCES public."InspectionTemplates" ("Id") ON DELETE CASCADE;
            
            ALTER TABLE public."Inspections" ADD CONSTRAINT "FK_Inspections_InspectionTemplates_TemplateId"
            FOREIGN KEY ("TemplateId") REFERENCES public."InspectionTemplates" ("Id") ON DELETE RESTRICT;
            
            ALTER TABLE public."InspectionQuestions" ADD CONSTRAINT "FK_InspectionQuestions_Inspections_InspectionId"
            FOREIGN KEY ("InspectionId") REFERENCES public."Inspections" ("Id") ON DELETE CASCADE;
            
            CREATE INDEX "IX_TemplateQuestions_InspectionTemplateId"
                ON public."TemplateQuestions" ("InspectionTemplateId");
            CREATE INDEX "IX_Inspections_TemplateId" ON public."Inspections" ("TemplateId");
            CREATE UNIQUE INDEX "IX_InspectionQuestions_InspectionId_Position"
                ON public."InspectionQuestions" ("InspectionId", "Position");
            CREATE UNIQUE INDEX "IX_InspectionQuestions_InspectionId_SourceQuestionId"
                ON public."InspectionQuestions" ("InspectionId", "SourceQuestionId");
            
            -- Previously implemented domain properties, not yet migrated in the uploaded source.
            ALTER TABLE public."InspectionQuestions"
                ADD COLUMN "Answer" character varying(20) NULL,
                ADD COLUMN "Comment" character varying(2000) NULL;
            
            DO $verify$
            DECLARE
                entry record;
                actual_count bigint;
            BEGIN
                FOR entry IN SELECT * FROM "InspectNow_IdConversionCounts" LOOP
                    EXECUTE format('SELECT count(*) FROM public.%I', entry."EntityTable")
                        INTO actual_count;
                    IF actual_count <> entry."RowCount" THEN
                        RAISE EXCEPTION 'Row count changed for %', entry."EntityTable";
                    END IF;
                END LOOP;
            END;
            $verify$;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        // New numeric records have no original UUID. A blind reverse conversion
        // would also discard answer data. Restore the pre-upgrade backup with
        // its matching source commit if a full rollback is needed.
        throw new NotSupportedException(
            "This data-preserving ID conversion is forward-only. Restore the " +
            "pre-migration database backup and matching source commit to roll back.");
    }
}
